# Generated by Django 5.1.7 on 2025-03-29 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Igreja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('cidade', models.CharField(max_length=100)),
                ('estado', models.CharField(max_length=2)),
                ('endereco', models.TextField()),
                ('contato', models.CharField(max_length=50)),
                ('imagem_da_igreja', models.ImageField(blank=True, null=True, upload_to='imagens_igrejas/')),
            ],
        ),
    ]
