# Generated by Django 5.1.7 on 2025-03-29 18:34

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('igrejas', '0002_alter_igreja_contato_alter_igreja_endereco'),
    ]

    operations = [
        migrations.AlterField(
            model_name='igreja',
            name='imagem_da_igreja',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='imagem_da_igreja'),
        ),
    ]
