services:
  - type: web
    name: igreja-manager
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn igreja_manager.wsgi:application
    postDeployScript: |
      python manage.py migrate
      python manage.py collectstatic --noinput
      python create_superuser.py
