services:
  - type: web
    name: igreja-manager
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn igreja_manager.wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: igreja_manager.settings
      - key: SECRET_KEY
        value: sua-chave-secreta-aqui
      - key: DEBUG
        value: False
