# Generated by Django 5.1.7 on 2025-03-29 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membros', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membro',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='membro',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
