# Generated by Django 5.1.7 on 2025-03-29 15:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('membros', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comprovante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tipo', models.CharField(choices=[('D', 'Dízimo'), ('O', 'Oferta')], max_length=1)),
                ('data_comprovante', models.DateField()),
                ('arquivo', models.FileField(upload_to='comprovantes/')),
                ('membro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comprovantes', to='membros.membro')),
            ],
        ),
    ]
