# Generated by Django 5.1.7 on 2025-03-29 18:34

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comprovantes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comprovante',
            name='arquivo',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='arquivo'),
        ),
    ]
