# Generated by Django 5.1.7 on 2025-03-30 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comprovantes', '0002_alter_comprovante_arquivo'),
    ]

    operations = [
        migrations.AddField(
            model_name='comprovante',
            name='forma_pagamento',
            field=models.CharField(choices=[('P', 'Pix/Deposito'), ('D', 'Dinheiro'), ('C', 'Cartão'), ('A', 'A Confirmar')], default='A', max_length=1),
        ),
    ]
